version: "3.1"
services:
  elasticsearch:
    image: daocloud.io/library/elasticsearch:6.5.4
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: daocloud.io/library/kibana:6.5.4
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - elasticsearch_url=ip
    depends_on:
      - elasticsearch